services:
  app:
    # image: "php:8.4-fpm"
    build:
      context: .
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env

  database:
    image: "postgres:17-alpine"
    container_name: database
    working_dir: /app
    volumes:
      - ".:/app"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "5432:5432"

  nginx:
    image: "nginx:alpine"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
